#!/bin/sh
# Rebuild db/<database>/{schema,seed}/*.sql and db/manifest.txt mechanically
# from a known-good source.
#
# The codified SQL under db/ is GENERATED. Never hand-edit it: fix the source
# (or this script) and re-run. Hand-editing is how the previous two attempts
# silently lost data.
#
# Source is, by default, the archived dumps in docs/historical/db-dumps/.
# To regenerate from a live database instead:
#
#     SOURCE_MODE=live SOURCE_SUFFIX= sh db/tools/regenerate.sh
#
# ...which reads the real `rift_core` / `rift` databases rather than loading
# the dumps into scratch copies first.
set -eu

DB_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
REPO_DIR=$(CDPATH= cd -- "$DB_DIR/.." && pwd)
DUMP_DIR="${DUMP_DIR:-$REPO_DIR/docs/historical/db-dumps}"

MYSQL="${MYSQL:-sudo mysql}"
MYSQLDUMP="${MYSQLDUMP:-sudo mysqldump}"

DATABASES="rift_core rift"

# Tables that must load before their alphabetical position would place them.
# Format: "<database>:<table> <table> ..." — listed tables are hoisted to the
# front of that database's order, in the order given; everything else follows
# alphabetically.
#
# world_areas currently sorts before world_rooms anyway, but that is an
# accident of the alphabet, not a guarantee. Encoding the intent here means a
# future table cannot quietly break the ordering.
PRIORITY_rift_core="world_areas"
PRIORITY_rift=""

# Dump flags shared by schema and seed:
#   --skip-dump-date  keeps regeneration diffs empty when nothing changed
#   --single-transaction is deliberately NOT used: these tables are MyISAM,
#                        which is non-transactional, so it would be a no-op.
COMMON_FLAGS="--skip-dump-date"

# SOURCE_MODE=dump  (default) load docs/historical/db-dumps/<db>.sql into a
#                   scratch DB named <db>_regen_src and dump from that.
# SOURCE_MODE=live  read <db> directly.
SOURCE_MODE="${SOURCE_MODE:-dump}"
SOURCE_SUFFIX="${SOURCE_SUFFIX-_regen_src}"

# mysqldump stamps the source database name into a header comment. In dump
# mode that name is the scratch DB, which is both confusing in a committed
# file and a source of spurious diffs between dump-mode and live-mode
# regeneration. Rewrite it to the real database name.
normalize_header() {
    sed -e "s/^-- Host: .*    Database: .*/-- Database: $1/"
}

priority_for() {
    case "$1" in
        rift_core) echo "$PRIORITY_rift_core" ;;
        rift)      echo "$PRIORITY_rift" ;;
        *)         echo "" ;;
    esac
}

# Order a database's tables: priority tables first (in declared order), then
# the remainder alphabetically.
ordered_tables() {
    _db=$1
    _src=$2
    _priority=$(priority_for "$_db")

    _all=$($MYSQL -N -B -e \
        "SELECT table_name FROM information_schema.tables
          WHERE table_schema='$_src' AND table_type='BASE TABLE'
          ORDER BY table_name;")

    for _p in $_priority; do
        echo "$_all" | grep -qx "$_p" || {
            echo "regenerate: priority table '$_p' not found in $_src" >&2
            exit 1
        }
        echo "$_p"
    done

    for _t in $_all; do
        _skip=0
        for _p in $_priority; do
            [ "$_t" = "$_p" ] && _skip=1
        done
        [ "$_skip" -eq 0 ] && echo "$_t"
    done
}

MANIFEST="$DB_DIR/manifest.txt"
{
    echo "# GENERATED by db/tools/regenerate.sh -- do not hand-edit."
    echo "#"
    echo "# Ordered load list driving db/install.sh. All schema rows for a"
    echo "# database run before its seed rows. Columns are whitespace-separated:"
    echo "#"
    echo "#   <database>  <phase>  <table>"
    echo "#"
} > "$MANIFEST"

for db in $DATABASES; do
    if [ "$SOURCE_MODE" = "dump" ]; then
        src="${db}${SOURCE_SUFFIX}"
        dump="$DUMP_DIR/$db.sql"
        [ -f "$dump" ] || { echo "regenerate: missing dump $dump" >&2; exit 1; }
        echo "Loading $dump into scratch database $src"
        $MYSQL -e "DROP DATABASE IF EXISTS \`$src\`; CREATE DATABASE \`$src\`;"
        $MYSQL "$src" < "$dump"
    else
        src="$db"
        echo "Reading live database $src"
    fi

    schema_dir="$DB_DIR/$db/schema"
    seed_dir="$DB_DIR/$db/seed"
    rm -rf "$schema_dir" "$seed_dir"
    mkdir -p "$schema_dir" "$seed_dir"

    tables=$(ordered_tables "$db" "$src")

    for table in $tables; do
        echo "  $db.$table"
        $MYSQLDUMP $COMMON_FLAGS --no-data "$src" "$table" | normalize_header "$db" > "$schema_dir/$table.sql"
        # Default (extended) INSERT batching respects net_buffer_length, so no
        # single statement approaches max_allowed_packet. This is what removes
        # the need for the old hand-managed world_rooms_1..4 chunking.
        $MYSQLDUMP $COMMON_FLAGS --no-create-info "$src" "$table" | normalize_header "$db" > "$seed_dir/$table.sql"
    done

    for table in $tables; do echo "$db	schema	$table" >> "$MANIFEST"; done
    echo "" >> "$MANIFEST"
    for table in $tables; do echo "$db	seed	$table" >> "$MANIFEST"; done
    echo "" >> "$MANIFEST"

    if [ "$SOURCE_MODE" = "dump" ] && [ -n "$SOURCE_SUFFIX" ]; then
        $MYSQL -e "DROP DATABASE IF EXISTS \`$src\`;"
    fi
done

echo "Regenerated schema/, seed/, and manifest.txt. Run db/tools/verify.sh next."
