areas:
- area/**

characters:
- code/characterClasses/**

tests:
- tests/**

admin:
- admin/**

docs:
- docs/**

core:
- code/**

setup:
- Makefile
- *.sql
- *.sh

dev-install:
- dev-install.sh

db:
- db/**

db-rift:
- db/rift/**

db-rift-core:
- db/rift_core/**