//
// The gsn_* skill numbers, in one place.
//
// Each name is an index into skill_table, assigned at boot from the row that
// names it.  This file is included wherever the list is needed, with GSN
// defined to do the work: db.h declares them, db.c defines them and builds the
// registry boot checks against.  Declaring and defining from one list is what
// keeps the two from drifting -- they used to be maintained by hand and had
// three duplicates and nineteen definitions no header mentioned.
//
// The second column says what the name is FOR, because nothing else can:
//
//   Wired    a skill_table row must name it, and boot reports it if none does
//   Pending  reserved for a feature that is not implemented yet; boot is silent
//   Tag      an affect label with no skill of its own; needs a unique value
//
// Pending is the state to use for a new name.  Promote it to Wired in the same
// change that gives the skill its table row, which is what turns the check on.
//
// There is deliberately no include guard: this file is included more than once,
// with a different GSN each time.
//

// Named but never created.  Uncomment to reserve the name.
//GSN(gsn_battlecry, Pending)
//GSN(gsn_empower, Pending)
//GSN(gsn_power_word_fear, Pending)
//GSN(gsn_steel_nerves, Pending)
//GSN(gsn_bandage, Pending)
//GSN(gsn_flurry, Pending)				// Quest flurry -Dioxide
//GSN(gsn_drum, Pending)				// Quest drum -Dioxide
//GSN(gsn_executioner, Pending)
//GSN(gsn_phat_blunt, Pending)


GSN(gsn_timer, Wired)
GSN(gsn_repose, Wired)
GSN(gsn_medicine, Wired)
GSN(gsn_somatic_casting, Wired)
GSN(gsn_frigidaura, Wired)
GSN(gsn_stasis_wall, Wired)
GSN(gsn_integrate, Wired)
GSN(gsn_sensevibrations, Wired)
GSN(gsn_diamondskin, Wired)
GSN(gsn_hardenfist, Wired)
GSN(gsn_jackal, Wired)
GSN(gsn_mangled, Wired)
GSN(gsn_rage, Wired)
GSN(gsn_horde_communion, Wired)
GSN(gsn_bleeding, Wired)
GSN(gsn_calm, Wired)
GSN(gsn_agitate, Wired)
GSN(gsn_immolate, Wired)
GSN(gsn_enervate, Wired)
GSN(gsn_corona, Wired)
GSN(gsn_infravision, Wired)
GSN(gsn_faerie_fire, Wired)
GSN(gsn_faerie_fog, Wired)
GSN(gsn_backstab, Wired)
GSN(gsn_detect_hidden, Wired)
GSN(gsn_detect_movement, Wired)
GSN(gsn_bluff, Wired)
GSN(gsn_dodge, Wired)
GSN(gsn_envenom, Wired)
GSN(gsn_hide, Wired)
GSN(gsn_peek, Wired)
GSN(gsn_pick_lock, Wired)
GSN(gsn_sneak, Wired)
GSN(gsn_steal, Wired)
GSN(gsn_silence, Wired)
GSN(gsn_disarm, Wired)
GSN(gsn_enhanced_damage, Wired)
GSN(gsn_kick, Wired)
GSN(gsn_parry, Wired)
GSN(gsn_rescue, Wired)
GSN(gsn_second_attack, Wired)
GSN(gsn_third_attack, Wired)
GSN(gsn_fourth_attack, Wired)

GSN(gsn_divine_frenzy, Wired)
GSN(gsn_awe, Wired)
GSN(gsn_strike_of_virtue, Wired)

GSN(gsn_decrepify, Wired)
GSN(gsn_displacement, Wired)
GSN(gsn_false_motives, Wired)

GSN(gsn_blindness, Wired)
GSN(gsn_chill_touch, Wired)
GSN(gsn_burning_hands, Wired)
GSN(gsn_charm_person, Wired)
GSN(gsn_curse, Wired)
GSN(gsn_invis, Wired)
GSN(gsn_mass_invis, Wired)
GSN(gsn_poison, Wired)
GSN(gsn_plague, Wired)
GSN(gsn_sleep, Wired)
GSN(gsn_sanctuary, Wired)
GSN(gsn_fly, Wired)

/* new gsn's */
GSN(gsn_axe, Wired)
GSN(gsn_dagger, Wired)
GSN(gsn_flail, Wired)
GSN(gsn_mace, Wired)
GSN(gsn_polearm, Wired)
GSN(gsn_shield_block, Wired)
GSN(gsn_spear, Wired)
GSN(gsn_sword, Wired)
GSN(gsn_whip, Wired)

GSN(gsn_bash, Wired)
GSN(gsn_berserk, Wired)
GSN(gsn_dirt, Wired)
GSN(gsn_hand_to_hand, Wired)
GSN(gsn_trip, Wired)

GSN(gsn_fast_healing, Wired)
GSN(gsn_haggle, Wired)
GSN(gsn_lore, Wired)
GSN(gsn_meditation, Wired)

GSN(gsn_scrolls, Wired)
GSN(gsn_staves, Wired)
GSN(gsn_wands, Wired)
GSN(gsn_recall, Wired)

GSN(gsn_mimic, Pending)
GSN(gsn_liquify, Pending)
GSN(gsn_morph_weapon, Pending)

GSN(gsn_ground_control, Wired)

GSN(gsn_absorb, Wired)
GSN(gsn_camouflage, Wired)
GSN(gsn_acute_vision, Wired)
GSN(gsn_ambush, Wired)
GSN(gsn_laying_hands, Wired)
GSN(gsn_circle, Wired)
GSN(gsn_dual_backstab, Wired)
GSN(gsn_skin, Wired)
GSN(gsn_camp, Wired)
GSN(gsn_animate_dead, Wired)
GSN(gsn_barkskin, Wired)
GSN(gsn_animal_call, Wired)
GSN(gsn_aura_of_sustenance, Pending)
GSN(gsn_shadowgate, Pending)
GSN(gsn_eye_of_the_predator, Pending)
GSN(gsn_blackjack, Wired)
GSN(gsn_dual_wield, Wired)
GSN(gsn_trance, Wired)
GSN(gsn_wanted, Pending)
GSN(gsn_cleave, Wired)
GSN(gsn_herb, Wired)
GSN(gsn_protective_shield, Wired)
GSN(gsn_consecrate, Wired)
GSN(gsn_true_sight, Pending)
GSN(gsn_butcher, Pending)
GSN(gsn_vanish, Wired)
GSN(gsn_embalm, Wired)
GSN(gsn_counter, Wired)
GSN(gsn_acid_spit, Pending)
GSN(gsn_bear_call, Wired)
GSN(gsn_trophy, Wired)
GSN(gsn_tail, Wired)
GSN(gsn_spellbane, Pending)
GSN(gsn_request, Wired)
GSN(gsn_endure, Wired)
GSN(gsn_throw, Wired)
GSN(gsn_nerve, Wired)
GSN(gsn_poison_dust, Wired)
GSN(gsn_blindness_dust, Wired)
GSN(gsn_strangle, Wired)
GSN(gsn_warcry, Wired)
GSN(gsn_chimera_lion, Wired)
GSN(gsn_chimera_goat, Wired)
GSN(gsn_strange_form, Wired)
GSN(gsn_enlist, Wired)
GSN(gsn_shadowplane, Pending)
GSN(gsn_blackjack_timer, Wired)
GSN(gsn_strangle_timer, Pending)
GSN(gsn_tame, Wired)
GSN(gsn_track, Pending)
GSN(gsn_find_water, Wired)
GSN(gsn_shield_cleave, Wired)
GSN(gsn_spellcraft, Wired)
GSN(gsn_cloak_form, Wired)
GSN(gsn_demand, Wired)
GSN(gsn_shapeshift, Wired)
GSN(gsn_regeneration, Wired)
GSN(gsn_parrot, Wired)
GSN(gsn_door_bash, Wired)

GSN(gsn_headbutt, Wired)
GSN(gsn_gore, Wired)
GSN(gsn_scorch, Wired)
GSN(gsn_shattered_bone, Wired)
GSN(gsn_forget, Wired)
GSN(gsn_earthbind, Wired)
GSN(gsn_divine_touch, Wired)
GSN(gsn_forage, Wired)
GSN(gsn_assassinate, Wired)
GSN(gsn_defend, Wired)
GSN(gsn_intimidate, Wired)
GSN(gsn_escape, Wired)
GSN(gsn_moving_ambush, Wired)
GSN(gsn_pugil, Wired)
GSN(gsn_staff, Wired)

GSN(gsn_turn_undead, Wired)
GSN(gsn_spiritual_hammer, Wired)
GSN(gsn_crimson_martyr, Wired)
GSN(gsn_benevolence, Wired)
GSN(gsn_intercept, Wired)
GSN(gsn_champions_defense, Wired)
GSN(gsn_indomitable_spirit, Wired)
GSN(gsn_protection_heat_cold, Wired)

GSN(gsn_rally, Wired)
GSN(gsn_tactics, Wired)
GSN(gsn_lash, Wired)
GSN(gsn_prevent_healing, Wired)
GSN(gsn_quiet_movement, Wired)
GSN(gsn_iron_resolve, Wired)

GSN(gsn_atrophy, Wired)
GSN(gsn_stoneskin, Wired)
GSN(gsn_shield, Wired)
GSN(gsn_starvation, Wired)
GSN(gsn_spore, Pending)
GSN(gsn_barbarian_strike, Pending)
GSN(gsn_barbarian_bone_tear, Pending)
GSN(gsn_dehydrated, Wired)			// For starve/thirst
GSN(gsn_hold_person, Wired)			// Hold person -Detlef
GSN(gsn_knife, Wired)				// Thief knife -Dioxide
GSN(gsn_disperse, Wired)				// Disperse for Outlaw -Dioxide
GSN(gsn_lightwalk, Pending)			// Quest lightwalk -Dioxide
GSN(gsn_sanguine_ward, Wired)
GSN(gsn_bind, Wired)
GSN(gsn_deafen, Wired)				// Deafen for AP -Detlef
GSN(gsn_divine_intervention, Wired)	// divine intervention -Dioxide
GSN(gsn_creep, Wired)				// creep skill -Dioxide
GSN(gsn_unholy_timer, Wired)
GSN(gsn_parting_blow, Wired)
GSN(gsn_mysterious_dream, Pending)
GSN(gsn_pincer, Wired)
GSN(gsn_devour, Wired)
GSN(gsn_keen_vision, Wired)
GSN(gsn_vampiric_touch, Wired)
GSN(gsn_snare, Wired)
GSN(gsn_snaretimer, Wired)
GSN(gsn_soften, Wired)
GSN(gsn_blade_barrier, Wired)
GSN(gsn_sunray, Wired)
GSN(gsn_enlarge, Wired)
GSN(gsn_mana_drain, Wired)
GSN(gsn_worldbind, Wired)
GSN(gsn_sceptre, Wired)
GSN(gsn_sceptret, Wired)
GSN(gsn_dark_blessing, Wired)
GSN(gsn_web, Wired)
GSN(gsn_volley, Wired)



GSN(gsn_talismanic, Wired)
GSN(gsn_hex, Wired)
GSN(gsn_visceral, Wired)
GSN(gsn_conflagration, Wired)
GSN(gsn_gravity_well, Wired)
GSN(gsn_ultradiffusion, Wired)
GSN(gsn_molecular_disjunction, Wired)
GSN(gsn_vacuum, Wired)
GSN(gsn_cyclone_forming, Wired)
GSN(gsn_cyclone, Wired)
GSN(gsn_incandescense, Wired)
GSN(gsn_diuretic, Wired)
GSN(gsn_earthquake, Wired)
GSN(gsn_mana_conduit, Wired)
GSN(gsn_synaptic_enhancement, Wired)
GSN(gsn_synaptic_impairment, Wired)
GSN(gsn_interference, Wired)
GSN(gsn_elecshield, Wired)
GSN(gsn_abite, Wired)
GSN(gsn_lbite, Wired)
GSN(gsn_hydroperception, Wired)
GSN(gsn_watershield, Wired)
GSN(gsn_flood, Wired)
GSN(gsn_tidalwave, Wired)
GSN(gsn_riptide, Wired)
GSN(gsn_watermeld, Wired)
GSN(gsn_sense_disturbance, Wired)
GSN(gsn_travelease, Wired)
GSN(gsn_stability, Wired)
GSN(gsn_crush, Pending)
GSN(gsn_earthshield, Wired)
GSN(gsn_coldshield, Wired)
GSN(gsn_heatshield, Wired)
GSN(gsn_chill, Wired)
GSN(gsn_reduce, Wired)
GSN(gsn_airshield, Wired)
GSN(gsn_coagulate, Wired)
GSN(gsn_unholy_bond, Wired)
GSN(gsn_drive, Wired)
GSN(gsn_hypothermia, Wired)
GSN(gsn_retreat, Wired)
GSN(gsn_dash, Wired)
GSN(gsn_imprisonvoice, Wired)
GSN(gsn_howl, Wired)
GSN(gsn_scramble_neurons, Wired)
GSN(gsn_acid_vein, Wired)
GSN(gsn_acid_stream, Wired)
GSN(gsn_corrode_lock, Wired)
GSN(gsn_attract, Wired)
GSN(gsn_call_lightning, Wired)
GSN(gsn_grounding, Wired)
GSN(gsn_neutralize, Wired)
GSN(gsn_caustic_vapor, Wired)
GSN(gsn_noxious_fumes, Wired)
GSN(gsn_drain, Wired)
GSN(gsn_smokescreen, Wired)
GSN(gsn_shroud_of_secrecy, Wired)
GSN(gsn_smother, Wired)
GSN(gsn_noxious_ward, Wired)
GSN(gsn_blanket, Wired)
GSN(gsn_accumulate_heat, Wired)
GSN(gsn_earthsembrace, Wired)
GSN(gsn_melt_rock, Wired)
GSN(gsn_magma_tunnel, Wired)
GSN(gsn_heat_earth, Pending)
GSN(gsn_whiteout, Wired)
GSN(gsn_unbreakable, Wired)
GSN(gsn_freeze_door, Wired)
GSN(gsn_frost_growth, Wired)
GSN(gsn_bind_feet, Wired)
GSN(gsn_glaciate, Wired)
GSN(gsn_stalactites, Wired)
GSN(gsn_ice_blast, Wired)
GSN(gsn_icy_carapace, Wired)
GSN(gsn_sheath_of_ice, Wired)
GSN(gsn_ironskin, Wired)
GSN(gsn_burden, Wired)
GSN(gsn_cloak_of_mist, Wired)
GSN(gsn_airy_water, Wired)
GSN(gsn_cooling_mist, Wired)
GSN(gsn_creeping_tomb, Wired)
GSN(gsn_pass_without_trace, Wired)
GSN(gsn_quicksand, Wired)
GSN(gsn_quicksand_sinking, Wired)
GSN(gsn_earthfade, Wired)
GSN(gsn_rust, Wired)
GSN(gsn_puddle, Wired)
GSN(gsn_indom, Wired)
GSN(gsn_traitors_luck, Wired)
GSN(gsn_darksight, Wired)
GSN(gsn_bloodlust, Wired)
GSN(gsn_unholy_communion, Wired)
GSN(gsn_lesser_demon, Wired)
GSN(gsn_greater_demon, Wired)
GSN(gsn_gamygyn_soul, Wired)
GSN(gsn_orobas_soul, Wired)
GSN(gsn_dark_familiar, Wired)
GSN(gsn_word_of_command, Wired)
GSN(gsn_mark_of_wrath, Wired)
GSN(gsn_baals_mastery, Wired)
GSN(gsn_living_blade, Wired)
GSN(gsn_leech, Wired)
GSN(gsn_plasma_arc, Wired)
GSN(gsn_sphere_of_plasma, Wired)
GSN(gsn_essence_of_plasma, Wired)
GSN(gsn_plasma_cube, Wired)
GSN(gsn_plasma_thread, Wired)
GSN(gsn_fashion_crystal, Wired)
GSN(gsn_farsee, Wired)
GSN(gsn_blinding_orb, Wired)
GSN(gsn_rotating_ward, Wired)
GSN(gsn_plant, Wired)
GSN(gsn_gag, Wired)
GSN(gsn_drag, Wired)
GSN(gsn_palm, Wired)
GSN(gsn_trail, Wired)
GSN(gsn_tripwire, Wired)
GSN(gsn_sign, Wired)
GSN(gsn_slash, Wired)
GSN(gsn_stash, Wired)
GSN(gsn_avoid, Wired)
GSN(gsn_disguise, Wired)
GSN(gsn_shadow_cloak, Wired)
GSN(gsn_stealth, Wired)
GSN(gsn_counterfeit, Wired)
GSN(gsn_strip, Wired)
GSN(gsn_silent_movement, Wired)
GSN(gsn_infidels_weight, Wired)
GSN(gsn_burning_vision, Wired)
GSN(gsn_divine_ward, Wired)
GSN(gsn_scribe, Wired)
GSN(gsn_healing_sleep, Wired)
GSN(gsn_deny_magic, Wired)
GSN(gsn_nullify, Wired)
GSN(gsn_bane, Wired)
GSN(gsn_gking, Tag)
GSN(gsn_lesser_golem, Wired)
GSN(gsn_greater_golem, Wired)
GSN(gsn_aggressor, Wired)
GSN(gsn_subdue, Wired)
GSN(gsn_drowning, Wired)
GSN(gsn_hunters_awareness, Pending)
GSN(gsn_hunters_stealth, Pending)
GSN(gsn_hunters_net, Wired)
GSN(gsn_severed, Wired)


GSN(gsn_group_retreat, Wired)
GSN(gsn_arms_of_light, Wired)
GSN(gsn_arms_of_wrath, Wired)
GSN(gsn_arms_of_purity, Wired)
GSN(gsn_arms_of_judgement, Wired)
GSN(gsn_holy_shroud, Wired)
GSN(gsn_seraphic_mantle, Wired)
GSN(gsn_shield_of_faith, Wired)
GSN(gsn_rites_of_preparation, Wired)
GSN(gsn_channeling, Wired)
GSN(gsn_empathy, Wired)
GSN(gsn_altruism, Wired)
GSN(gsn_tower_of_fortitude, Wired)
GSN(gsn_shadowsense, Wired)
GSN(gsn_fervor, Wired)
GSN(gsn_piety, Wired)
GSN(gsn_spiritual_healing, Wired)
GSN(gsn_retribution, Wired)
GSN(gsn_shroud_of_light, Wired)
GSN(gsn_infidels_fate, Wired)
GSN(gsn_mana_sickness, Wired)
GSN(gsn_mana_infusion, Wired)
GSN(gsn_tangleroot, Wired)


//
// Gladiator
//

GSN(gsn_fend, Wired)
GSN(gsn_entrap, Wired)
GSN(gsn_gouge, Wired)
GSN(gsn_hobble, Wired)
GSN(gsn_crippling_blow, Wired)
GSN(gsn_bleed, Wired)

//
// Duelist
//

GSN(gsn_maneuvering, Wired)
GSN(gsn_catch, Wired)
GSN(gsn_posture, Wired)
GSN(gsn_unbalance, Wired)
GSN(gsn_sidestep, Wired)
GSN(gsn_concuss, Wired)
GSN(gsn_disrupt_formation, Wired)

//
// Barbarian
//

GSN(gsn_brutality, Wired)
GSN(gsn_shatter, Wired)
GSN(gsn_uppercut, Wired)
GSN(gsn_impale, Wired)
GSN(gsn_overhead, Wired)
GSN(gsn_batter, Wired)


//
// Dragoon
//

GSN(gsn_exchange, Wired)
GSN(gsn_charge, Wired)
GSN(gsn_deflect, Wired)
GSN(gsn_ease, Wired)
GSN(gsn_brace, Wired)
GSN(gsn_shieldbash, Wired)


//
// Skirmisher
//

GSN(gsn_evasion, Wired)
GSN(gsn_hurl, Wired)
GSN(gsn_dart, Wired)
GSN(gsn_cracked_sternum, Wired)
GSN(gsn_bloody_eyes, Wired)
GSN(gsn_broken_arm, Wired)
GSN(gsn_entwine, Wired)
GSN(gsn_pull, Wired)
GSN(gsn_fifth_attack, Wired)
GSN(gsn_whirlwind, Wired)

//
// Tactician
//

GSN(gsn_leadership, Wired)
GSN(gsn_assess, Wired)
GSN(gsn_exploit, Wired)
GSN(gsn_outflank, Wired)
GSN(gsn_terrain_mastery, Wired)
GSN(gsn_analyze, Wired)

//
// Style skills to keep track of percents
//

GSN(gsn_duelist_skill, Wired)
GSN(gsn_gladiator_skill, Wired)
GSN(gsn_barbarian_skill, Wired)
GSN(gsn_dragoon_skill, Wired)
GSN(gsn_skirmisher_skill, Wired)
GSN(gsn_tactician_skill, Wired)


GSN(gsn_rprog_elven_down, Tag)

//
// These had a definition and no declaration until this list became the single
// source of both.  They are placeholders like the rest.
//
GSN(gsn_circle_stab, Pending)
GSN(gsn_morph_red, Pending)
GSN(gsn_morph_black, Pending)
GSN(gsn_morph_blue, Pending)
GSN(gsn_morph_green, Pending)
GSN(gsn_morph_white, Pending)
GSN(gsn_morph_dragon, Pending)
GSN(gsn_breath_morph, Pending)
GSN(gsn_timestop, Pending)
GSN(gsn_timestop_done, Pending)
GSN(gsn_evaluation, Pending)
GSN(gsn_kinetic_shield, Pending)
GSN(gsn_cheap_shot, Pending)
GSN(gsn_incinerate, Pending)
GSN(gsn_ironhands, Pending)
GSN(gsn_legsweep, Pending)
GSN(gsn_whirl, Pending)
GSN(gsn_barrier, Pending)
GSN(gsn_aura, Pending)
