/* This file is auto-generated by Riftshadow Admin Website. Do not modify. */
#define	COL_BIT_LOOKUP_NAME		0
#define	COL_BIT_LOOKUP_BIT		1
#define	COL_BIT_LOOKUP_DEFINE		2
#define	COL_BIT_LOOKUP_TYPE		3
#define	COL_BIT_LOOKUP_NUM_BITS		4

#define	LOAD_BIT_LOOKUP(tvar)\
tvar.name.NoDeallocSetTo(row[COL_BIT_LOOKUP_NAME]);\
tvar.bit.SetToDouble(row[COL_BIT_LOOKUP_BIT]);\
tvar.define.NoDeallocSetTo(row[COL_BIT_LOOKUP_DEFINE]);\
tvar.type.NoDeallocSetTo(row[COL_BIT_LOOKUP_TYPE]);\
tvar.num_bits = row.RowToNumber(COL_BIT_LOOKUP_NUM_BITS);

#define	COL_CLASS_TABLE_NAME		1
#define	COL_CLASS_TABLE_WHO_NAME		2
#define	COL_CLASS_TABLE_ATTR_PRIME		3
#define	COL_CLASS_TABLE_ALIGN		4
#define	COL_CLASS_TABLE_WEAPON		5
#define	COL_CLASS_TABLE_GAINCONST		6
#define	COL_CLASS_TABLE_BASE_GROUP		7
#define	COL_CLASS_TABLE_DEFAULT_GROUP		8
#define	COL_CLASS_TABLE_CTYPE		9
#define	COL_CLASS_TABLE_STATUS		10

#define	LOAD_CLASS_TABLE(tvar)\
tvar->name.NoDeallocSetTo(row[COL_CLASS_TABLE_NAME]);\
tvar->who_name.NoDeallocSetTo(row[COL_CLASS_TABLE_WHO_NAME]);\
tvar->attr_prime = row.RowToNumber(COL_CLASS_TABLE_ATTR_PRIME);\
tvar->align = row.RowToNumber(COL_CLASS_TABLE_ALIGN);\
tvar->weapon = row.RowToNumber(COL_CLASS_TABLE_WEAPON);\
tvar->gainconst = row.RowToNumber(COL_CLASS_TABLE_GAINCONST);\
tvar->base_group.NoDeallocSetTo(row[COL_CLASS_TABLE_BASE_GROUP]);\
tvar->default_group.NoDeallocSetTo(row[COL_CLASS_TABLE_DEFAULT_GROUP]);\
tvar->ctype = row.RowToNumber(COL_CLASS_TABLE_CTYPE);\
tvar->status = row.RowToNumber(COL_CLASS_TABLE_STATUS);

#define	COL_CLIMATE_TABLE_NAME		0
#define	COL_CLIMATE_TABLE_NUMBER		1
#define	COL_CLIMATE_TABLE_SKYFREQS		2
#define	COL_CLIMATE_TABLE_TEMPFREQS		3

#define	LOAD_CLIMATE_TABLE(tvar)\
tvar.name.NoDeallocSetTo(row[COL_CLIMATE_TABLE_NAME]);\
tvar.number = row.RowToNumber(COL_CLIMATE_TABLE_NUMBER);\
tvar.skyfreqs.NoDeallocSetTo(row[COL_CLIMATE_TABLE_SKYFREQS]);\
tvar.tempfreqs.NoDeallocSetTo(row[COL_CLIMATE_TABLE_TEMPFREQS]);

#define	COL_D_LOOKUP_NAME		0
#define	COL_D_LOOKUP_ABBREV		1
#define	COL_D_LOOKUP_DEFINE		2
#define	COL_D_LOOKUP_CATEGORY		3
#define	COL_D_LOOKUP_VALUE		4

#define	LOAD_D_LOOKUP(tvar)\
tvar.name.NoDeallocSetTo(row[COL_D_LOOKUP_NAME]);\
tvar.abbrev.NoDeallocSetTo(row[COL_D_LOOKUP_ABBREV]);\
tvar.define.NoDeallocSetTo(row[COL_D_LOOKUP_DEFINE]);\
tvar.category.NoDeallocSetTo(row[COL_D_LOOKUP_CATEGORY]);\
tvar.value = row.RowToNumber(COL_D_LOOKUP_VALUE);

#define	COL_INTERP_TABLE_COMMAND_NAME		1
#define	COL_INTERP_TABLE_IMMEDIATE_EVAL		2
#define	COL_INTERP_TABLE_DO_FUN_NAME		3
#define	COL_INTERP_TABLE_MINIMUM_LEVEL		4
#define	COL_INTERP_TABLE_LOG_LEVEL		5
#define	COL_INTERP_TABLE_VISIBILITY		6

#define	LOAD_INTERP_TABLE(tvar)\
tvar.command_name.NoDeallocSetTo(row[COL_INTERP_TABLE_COMMAND_NAME]);\
tvar.immediate_eval = row.RowToNumber(COL_INTERP_TABLE_IMMEDIATE_EVAL);\
tvar.do_fun.SetPtr((void *)do_fun_table[i].name);\
tvar.minimum_level = row.RowToNumber(COL_INTERP_TABLE_MINIMUM_LEVEL);\
tvar.log_level = row.RowToNumber(COL_INTERP_TABLE_LOG_LEVEL);\
tvar.visibility.SetToDouble(row[COL_INTERP_TABLE_VISIBILITY]);

#define	COL_PLAYERS_NAME		0
#define	COL_PLAYERS_PASSWORD		1

#define	LOAD_PLAYERS(tvar)\
tvar.name.NoDeallocSetTo(row[COL_PLAYERS_NAME]);\
tvar.password.NoDeallocSetTo(row[COL_PLAYERS_PASSWORD]);

#define	COL_RACE_TABLE_NAME		1
#define	COL_RACE_TABLE_SHORT_NAME		2
#define	COL_RACE_TABLE_IMM_NAME		3
#define	COL_RACE_TABLE_RACE_TIME		4
#define	COL_RACE_TABLE_PCRACE		5
#define	COL_RACE_TABLE_RACE_STATUS		6
#define	COL_RACE_TABLE_ACT_FLAGS		7
#define	COL_RACE_TABLE_AFF_FLAGS		8
#define	COL_RACE_TABLE_OFF_FLAGS		9
#define	COL_RACE_TABLE_IMM_FLAGS		10
#define	COL_RACE_TABLE_RES_FLAGS		11
#define	COL_RACE_TABLE_VULN_FLAGS		12
#define	COL_RACE_TABLE_FORM_FLAGS		13
#define	COL_RACE_TABLE_BODY_PARTS		14
#define	COL_RACE_TABLE_ARMS		15
#define	COL_RACE_TABLE_LEGS		16
#define	COL_RACE_TABLE_SIZE		17
#define	COL_RACE_TABLE_AGE_MOD		18
#define	COL_RACE_TABLE_DEATHTIME		19
#define	COL_RACE_TABLE_ALIGN		20
#define	COL_RACE_TABLE_XP_ADD		21
#define	COL_RACE_TABLE_MAX_STR		22
#define	COL_RACE_TABLE_MAX_INT		23
#define	COL_RACE_TABLE_MAX_WIS		24
#define	COL_RACE_TABLE_MAX_DEX		25
#define	COL_RACE_TABLE_MAX_CON		26

#define	LOAD_RACE_TABLE(tvar)\
tvar.name.NoDeallocSetTo(row[COL_RACE_TABLE_NAME]);\
tvar.short_name.NoDeallocSetTo(row[COL_RACE_TABLE_SHORT_NAME]);\
tvar.imm_name.NoDeallocSetTo(row[COL_RACE_TABLE_IMM_NAME]);\
tvar.race_time.NoDeallocSetTo(row[COL_RACE_TABLE_RACE_TIME]);\
tvar.pcrace = row.RowToNumber(COL_RACE_TABLE_PCRACE);\
tvar.race_status = row.RowToNumber(COL_RACE_TABLE_RACE_STATUS);\
tvar.act_flags.SetToDouble(row[COL_RACE_TABLE_ACT_FLAGS]);\
tvar.aff_flags.SetToDouble(row[COL_RACE_TABLE_AFF_FLAGS]);\
tvar.off_flags.SetToDouble(row[COL_RACE_TABLE_OFF_FLAGS]);\
tvar.imm_flags.SetToDouble(row[COL_RACE_TABLE_IMM_FLAGS]);\
tvar.res_flags.SetToDouble(row[COL_RACE_TABLE_RES_FLAGS]);\
tvar.vuln_flags.SetToDouble(row[COL_RACE_TABLE_VULN_FLAGS]);\
tvar.form_flags.SetToDouble(row[COL_RACE_TABLE_FORM_FLAGS]);\
tvar.body_parts.SetToDouble(row[COL_RACE_TABLE_BODY_PARTS]);\
tvar.arms = row.RowToNumber(COL_RACE_TABLE_ARMS);\
tvar.legs = row.RowToNumber(COL_RACE_TABLE_LEGS);\
tvar.size = row.RowToNumber(COL_RACE_TABLE_SIZE);\
tvar.age_mod = row.RowToFloat(COL_RACE_TABLE_AGE_MOD);\
tvar.deathtime = row.RowToNumber(COL_RACE_TABLE_DEATHTIME);\
tvar.align = row.RowToNumber(COL_RACE_TABLE_ALIGN);\
tvar.xp_add = row.RowToNumber(COL_RACE_TABLE_XP_ADD);\
tvar.max_stats[0] = row.RowToNumber(COL_RACE_TABLE_MAX_STR);\
tvar.max_stats[1] = row.RowToNumber(COL_RACE_TABLE_MAX_INT);\
tvar.max_stats[2] = row.RowToNumber(COL_RACE_TABLE_MAX_WIS);\
tvar.max_stats[3] = row.RowToNumber(COL_RACE_TABLE_MAX_DEX);\
tvar.max_stats[4] = row.RowToNumber(COL_RACE_TABLE_MAX_CON);

#define	COL_SKILL_GROUPS_NAME		0
#define	COL_SKILL_GROUPS_SKILL		1

#define	LOAD_SKILL_GROUPS(tvar)\
tvar.name.NoDeallocSetTo(row[COL_SKILL_GROUPS_NAME]);\
tvar.skill.NoDeallocSetTo(row[COL_SKILL_GROUPS_SKILL]);

#define	COL_WORLD_AREAS_NAME		1
#define	COL_WORLD_AREAS_CREDITS		2
#define	COL_WORLD_AREAS_LOW_RANGE		3
#define	COL_WORLD_AREAS_HIGH_RANGE		4
#define	COL_WORLD_AREAS_MIN_VNUM		5
#define	COL_WORLD_AREAS_MAX_VNUM		6
#define	COL_WORLD_AREAS_TYPE		7
#define	COL_WORLD_AREAS_CLIMATE		8
#define	COL_WORLD_AREAS_FLAGS		9

#define	LOAD_WORLD_AREAS(tvar)\
tvar.name.NoDeallocSetTo(row[COL_WORLD_AREAS_NAME]);\
tvar.credits.NoDeallocSetTo(row[COL_WORLD_AREAS_CREDITS]);\
tvar.low_range = row.RowToNumber(COL_WORLD_AREAS_LOW_RANGE);\
tvar.high_range = row.RowToNumber(COL_WORLD_AREAS_HIGH_RANGE);\
tvar.min_vnum = row.RowToNumber(COL_WORLD_AREAS_MIN_VNUM);\
tvar.max_vnum = row.RowToNumber(COL_WORLD_AREAS_MAX_VNUM);\
tvar.type = row.RowToNumber(COL_WORLD_AREAS_TYPE);\
tvar.climate = row.RowToNumber(COL_WORLD_AREAS_CLIMATE);\
tvar.flags.SetToDouble(row[COL_WORLD_AREAS_FLAGS]);

#define	COL_WORLD_ROOMS_AREA_ID		0
#define	COL_WORLD_ROOMS_ROOM_ID		1
#define	COL_WORLD_ROOMS_VNUM		2
#define	COL_WORLD_ROOMS_NAME		3
#define	COL_WORLD_ROOMS_DESCRIPTION		4
#define	COL_WORLD_ROOMS_SECTOR_TYPE		5
#define	COL_WORLD_ROOMS_ROOM_FLAGS		6
#define	COL_WORLD_ROOMS_0_TO_ROOM		7
#define	COL_WORLD_ROOMS_0_EXIT_INFO		8
#define	COL_WORLD_ROOMS_0_KEY		9
#define	COL_WORLD_ROOMS_0_KEYWORD		10
#define	COL_WORLD_ROOMS_1_TO_ROOM		11
#define	COL_WORLD_ROOMS_1_EXIT_INFO		12
#define	COL_WORLD_ROOMS_1_KEY		13
#define	COL_WORLD_ROOMS_1_KEYWORD		14
#define	COL_WORLD_ROOMS_2_TO_ROOM		15
#define	COL_WORLD_ROOMS_2_EXIT_INFO		16
#define	COL_WORLD_ROOMS_2_KEY		17
#define	COL_WORLD_ROOMS_2_KEYWORD		18
#define	COL_WORLD_ROOMS_3_TO_ROOM		19
#define	COL_WORLD_ROOMS_3_EXIT_INFO		20
#define	COL_WORLD_ROOMS_3_KEY		21
#define	COL_WORLD_ROOMS_3_KEYWORD		22
#define	COL_WORLD_ROOMS_4_TO_ROOM		23
#define	COL_WORLD_ROOMS_4_EXIT_INFO		24
#define	COL_WORLD_ROOMS_4_KEY		25
#define	COL_WORLD_ROOMS_4_KEYWORD		26
#define	COL_WORLD_ROOMS_5_TO_ROOM		27
#define	COL_WORLD_ROOMS_5_EXIT_INFO		28
#define	COL_WORLD_ROOMS_5_KEY		29
#define	COL_WORLD_ROOMS_5_KEYWORD		30
#define	COL_WORLD_ROOMS_CABAL		31
#define	COL_WORLD_ROOMS_OWNER		32

#define	LOAD_EXIT_DATA(eptr)\
eptr->exit_info = eptr->RowToNumber(COL_WORLD_ROOMS_0_EXIT_INFO);\
eptr->key = eptr->RowToNumber(COL_WORLD_ROOMS_0_KEY);\
eptr->keyword.NoDeallocSetTo(COL_WORLD_ROOMS_0_KEYWORD);

#define	LOAD_WORLD_ROOMS(tvar)\
ASSOCIATE_AREA(tvar, row[COL_WORLD_ROOMS_AREA_ID]);\
tvar.area_id = row.RowToNumber(COL_WORLD_ROOMS_AREA_ID);\
tvar.room_id.SetToDouble(row[COL_WORLD_ROOMS_ROOM_ID]);\
tvar.vnum = row.RowToNumber(COL_WORLD_ROOMS_VNUM);\
tvar.name.NoDeallocSetTo(row[COL_WORLD_ROOMS_NAME]);\
tvar.description.NoDeallocSetTo(row[COL_WORLD_ROOMS_DESCRIPTION]);\
tvar.sector_type = row.RowToNumber(COL_WORLD_ROOMS_SECTOR_TYPE);\
tvar.room_flags.SetToDouble(row[COL_WORLD_ROOMS_ROOM_FLAGS]);\
tvar.cabal = row.RowToNumber(COL_WORLD_ROOMS_CABAL);\
tvar.owner.NoDeallocSetTo(row[COL_WORLD_ROOMS_OWNER]);\
ALLOCATE_EXITS(tvar);

#define	COL_WORLD_ROOMS_RID_ROOM_ID		0
#define	COL_WORLD_ROOMS_RID_VNUM		1

#define	LOAD_WORLD_ROOMS_RID(tvar)\
tvar.room_id = row.RowToNumber(COL_WORLD_ROOMS_RID_ROOM_ID);\
tvar.vnum = row.RowToNumber(COL_WORLD_ROOMS_RID_VNUM);

