name: Snyk Security

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  snyk:  
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    permissions:
      contents: read
      security-events: write
      actions: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@8e119fbb6c251787721d34ba683ed48eba792766

      - name: Snyk Code test
        run: snyk code test --sarif > snyk-code.sarif

      - name: Snyk Open Source monitor
        run: snyk monitor --all-projects

      - name: Snyk IaC test and report
        continue-on-error: true
        run: snyk iac test --report

      - name: Build a Docker image
        continue-on-error: true
        run: docker build -t your/image-to-test .

      - name: Snyk Container monitor
        continue-on-error: true
        run: snyk container monitor your/image-to-test --file=Dockerfile

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk-code.sarif